# Title shown in Application Information tab.
title: ODS Input variables schema
# Sub Title shown in Application Information tab.
description: ODS Input variables schema
schemaVersion: 1.1.0
version: "20190304"
locale: "en"
variableGroups:
  - title: "Provision in"
    variables:
      - ${region}
      - ${compartment_ocid}
  - title: "ODS Configuration"
    variables:
      - ${ods_compute_shape}
      - ${ods_storage_size}
      - ${ods_number_of_notebooks}
      - ${functions_enabled}
  - title: "Network Configuration"
    variables:
      - ${ods_vcn_use_existing}
      - ${ods_vcn_existing}
      - ${ods_vcn_name}
      - ${ods_vcn_cidr}
      - ${ods_subnet_public_existing}
      - ${ods_subnet_public_name}
      - ${ods_subnet_public_cidr}
      - ${ods_subnet_private_existing}
      - ${ods_subnet_private_name}
      - ${ods_subnet_private_cidr}

variables:
  ods_compute_shape:
    #type: oci:datascience:notebook:session:shapes:name
    type: enum
    enum:
      - VM.Standard.E2.2
      - VM.Standard.E2.4
      - VM.Standard.E2.8
      - VM.Standard2.1
      - VM.Standard2.2
      - VM.Standard2.4
      - VM.Standard2.8
      - VM.Standard2.16
      - VM.Standard2.24
    title: ODS Notebook Compute Shape
    required: true
    default: "VM.Standard.E2.2"
  ods_storage_size:
    type: integer
    required: true
    title: ODS Notebook Storage Size
    description: The size must be between 50 GB and 1,024 GB (1 TB)
    minimum: 50
    maximum: 1024
    default: 50
  ods_number_of_notebooks:
    type: integer
    required: true
    title: How many Notebooks would you like to create?
    minimum: 1
    default: 1
  region:
    type: oci:identity:region:name
    required: true
    visible: true
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    visible: true
  tenancy_ocid:
    type: string
    required: true
    visible: false
  ods_vcn_use_existing:
    type: boolean
    title: "Use Existing VCN?"
    required: true
    default: false
  ods_vcn_existing:
    type: oci:core:vcn:id
    title: "Select VCN"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
    visible: ${ods_vcn_use_existing}
  ods_subnet_public_existing:
    type: oci:core:subnet:id
    title: "Select Your Public VCN"
    description: "Hosts ODS Project, Notebooks (and API Gateway if functions is enabled)"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${ods_vcn_existing}
      hidePrivateSubnet: true
    required: true
    visible: ${ods_vcn_use_existing}
  ods_subnet_private_existing:
    type: oci:core:subnet:id
    title: "Select Your Private VCN"
    description: "Hosts Functions if enabled"
    required: ${ods_vcn_use_existing}
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${ods_vcn_existing}
      hidePublicSubnet: true
    visible:
      and:
        - ${ods_vcn_use_existing}
        - ${functions_enabled}
  ods_vcn_name:
    type: string
    title: "VCN Name"
    required: true
    default: "Data Science VCN"
    visible:
      not:
        - ${ods_vcn_use_existing}
  ods_vcn_cidr:
    type: string
    title: "VCN CIDR Space"
    required: true
    default: "10.0.0.0/16"
    visible:
      not:
        - ${ods_vcn_use_existing}
  ods_subnet_public_name:
    type: string
    title: "Public Subnet Name"
    description: "Hosts ODS Project, Notebooks (and API Gateway if functions is enabled)"
    required: true
    default: "Data Science - Public"
    visible:
      not:
        - ${ods_vcn_use_existing}
  ods_subnet_public_cidr:
    type: string
    title: "Public Subnet CIDR Space"
    required: true
    default: "10.0.0.0/24"
    visible:
      not:
        - ${ods_vcn_use_existing}
  ods_subnet_private_name:
    type: string
    title: "Private Subnet Name"
    description: "Hosts Functions if enabled"
    required: true
    default: "Data Science - Private"
    visible:
      and:
        - not:
            - ${ods_vcn_use_existing}
        - ${functions_enabled}
  ods_subnet_private_cidr:
    type: string
    title: "Private Subnet CIDR Space"
    required: true
    default: "10.0.1.0/24"
    visible:
      and:
        - not:
            - ${ods_vcn_use_existing}
        - ${functions_enabled}
  functions_enabled:
    type: boolean
    title: "Include Functions"
    required: true
    default: false
